# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

env:
  CI: true

on:
  push:
    branches:
      - main
    tags:
      - '!*'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com
      - run: npm install -g aws-sdk
      - run: npm ci
      # - run: npm publish
      - run: npx can-npm-publish --verbose && npm publish || echo "No need to publish"
        env:
          # NODE_AUTH_TOKEN: ${{secrets.npm_token}}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # バージョン情報を環境変数として設定
      - name: set version to env
        run: node -p -e '`VERSION=${require("./package.json").version}`' >> $GITHUB_ENV

      # バージョン情報持つタグを付与する
      - name: add version tag
        uses: pkgdeps/git-tag-action@v2
        with:
          version: ${{ env.VERSION }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          git_commit_sha: ${{ github.sha }}
          git_tag_prefix: 'v'
